### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by JohnMica** [muuvmuuv/grav-plugin-adsense#2]
when trying to install from within grav all there is is a blank page titled - about:blank.

could it be the links are not fully working in the package?

**Comment by muuvmuuv** [comment]
I did not really understand you problem. Where did you find this blank page. Maybe you can shot a screenshot or give me a link to find out what is wrong. @JohnMica

**Comment by JohnMica** [comment]
@muuvmuuv using admin in Grav, trying to install adsense all you get is a blank page. I have tried many times with localhost installs. I can install with terminal the plugin (still having issues trying to place the ads for now)
also as per the attached photo - it seems that the options within admin for the plugin are not rendering properly ?
![captura de ecran din 2016 03 18 la 15 14 25](https://cloud.githubusercontent.com/assets/7076631/13882261/a1b128c0-ed1c-11e5-9233-75ee027201e9.png)

**Comment by muuvmuuv** [comment]
Is that still a bug? Could you provide more information about GRAV (Version/Language etc.)

**Comment by Cordoha** [comment]
Issue still at large. I'm using Grav v1.2.4 with Admin v1.4.2, and the latest installation of Gantry. Using Firefox. Had the same issue without Gantry, so I don't think it matters sbout that.

**Comment by muuvmuuv** [comment]
@Cordoha I have changed the code and now using shortcode-core to implement adsense to your site. Could you try it and tell me if the error still exits, if so. Paste your system.yaml and other settings/pages in hastebin with a link. So I can reproduce the error.

Thanks

**Comment by JohnMica** [comment]
HI @muuvmuuv  all working good now.

Thanks for the update
