### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by kabilya** [muuvmuuv/grav-plugin-adsense#4]
Hi.
First of all , thank you very much for this handy plugin.
I already installed your plugin and entered my adsense client id
and ad-slot. Turned on the sandbox as well but not seeing any ad.
I am using the Notepad theme. Is there anything I need to change
or add to make it work?

Sorry if this is a really newbie question. I just installed grav today.

Thanks.

Christian

**Comment by justClouds** [comment]
Similar situation here... Frssh install of Grav using the Antimatter theme. Added the proposed entry in the yaml header of the modular page, but nothing is showing on that page.
Do I need to modify some twig temlate file?

**Comment by kabilya** [comment]
@justClouds 
Did you figure it out?

**Comment by justClouds** [comment]
Not yet. I did notice that the AdSense script on Google is called because when AdBlocker is active on the page I see an error calling these scripts in the debug window of the browser...

**Comment by kabilya** [comment]
I have it working. I created my own twig file. and just add the code generated by Adsense, just the ins part , and include the twig file in my post or page twig file.

**Comment by justClouds** [comment]
Sounds simple enough. Will try that too. Thanks.

**Comment by muuvmuuv** [comment]
I updated this repo. Now you can use adsense with the shortcode plugin. I'll add some other functionality as soon as possible. I donn't have enough time to do that private. @justClouds @kabilya
